### Create a new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Nike Butar Series 2",
  "code": "NB002",
  "description": "Nike Butar Series",
  "price": 3500000,
  "stock": 100,
  "categoryId": 2,
  "brandId": 1
}

### Update product
PUT http://localhost:8080/api/products/NB002
Content-Type: application/json

{
  "name": "Nike Butar Series Revolution",
  "description": "Nike Butar Series",
  "price": 2000000,
  "stock": 100,
  "categoryId": 2,
  "brandId": 1
}

### Get product
GET http://localhost:8080/api/products/NB002

### Delete product
PATCH http://localhost:8080/api/products/NB002

### Search product
GET http://localhost:8080/api/products/search?keyword=Nike&pageNumber=0&pageSize=10