### Create a new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Nike Butar Series",
  "code": "NB001",
  "description": "Nike Butar Series",
  "price": 3500000,
  "stock": 100,
  "categoryId": 2,
  "brandId": 1
}

### Update product
PUT http://localhost:8080/api/products/NB001
Content-Type: application/json

{
  "name": "Nike Butar Series Revolution",
  "description": "Nike Butar Series",
  "price": 2000000,
  "categoryId": 2,
  "brandId": 1
}

### Get product
GET http://localhost:8080/api/products/NB001

### Delete product
PATCH http://localhost:8080/api/products/NB001

### Search product
GET http://localhost:8080/api/products/search?keyword=Nike&pageNumber=0&pageSize=10